anyrepo/models/api.py
# AnyRepo
# Copyright (C) 2020  Anybox
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from enum import Enum
from typing import Optional
from uuid import uuid4

from anyrepo.api import API
from anyrepo.api.github_api import GithubAPI
from anyrepo.api.gitlab_api import GitlabAPI
from anyrepo.models import db
from anyrepo.models.encryption import decrypt_data, encrypt_data


class ApiType(Enum):
    """API supported by the app."""

    GITHUB = "github"
    GITLAB = "gitlab"

    def __str__(self):
        return str(self.name)


class ApiModel(db.Model):
    """API table."""

    __tablename__ = "api"

    id = db.Column(db.Integer, primary_key=True)
    slug = db.Column(
        db.String, nullable=False, default=lambda: uuid4().hex, unique=True
    )
    name = db.Column(db.String, nullable=False)
    url = db.Column(db.String, nullable=False, unique=True)
    api_type = db.Column(db.Enum(ApiType), nullable=False, name="type")
    token_encrypted = db.Column(db.LargeBinary, nullable=False, name="token")

    def set_token(self, token_value: str):
        """Encrypt token using app secret key and store it into token_encrypted
        field.
        """
        self.token_encrypted = encrypt_data(token_value)

    def get_token(self) -> str:
        """Get decrypted data from token_encrypted_field."""
        return decrypt_data(self.token_encrypted)

    def get_client(self) -> Optional[API]:
        """Get API client."""
        if self.api_type == ApiType.GITHUB:
            return GithubAPI(self.url, self.get_token())
        elif self.api_type == ApiType.GITLAB:
            return GitlabAPI(self.url, self.get_token())
        return None

anyrepo/models/hook.py
# AnyRepo
# Copyright (C) 2020  Anybox
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


from enum import Enum
from typing import TYPE_CHECKING, List
from uuid import uuid4

from anyrepo.models import db
from anyrepo.models.encryption import decrypt_data, encrypt_data

if TYPE_CHECKING:
    from anyrepo.models.request import RequestModel  # noqa: F401


class HookType(Enum):
    """API supported by the app."""

    GITHUB = "github"
    GITLAB = "gitlab"


class HookModel(db.Model):
    """Hook table."""

    __tablename__ = "hook"

    id = db.Column(db.Integer, primary_key=True)
    slug = db.Column(
        db.String, nullable=False, default=lambda: uuid4().hex, unique=True
    )
    endpoint = db.Column(db.String, nullable=False, unique=True)
    hook_type = db.Column(db.Enum(HookType), nullable=False, name="type")
    secret_encrypted = db.Column(db.LargeBinary, nullable=False, name="secret")

    requests = db.relationship("RequestModel", backref="hook", lazy=True)

    def set_secret(self, secret_value: str):
        """Encrypt secret using app secret key and store it into
        secret_encrypted field.
        """
        self.secret_encrypted = encrypt_data(secret_value)

    def get_secret(self) -> str:
        """Get decrypted data from secret_encrypted_field."""
        return decrypt_data(self.secret_encrypted)

    @property
    def good_requests(self) -> List["RequestModel"]:
        """Get good requests list."""
        return [request for request in self.requests if request.status == 200]

    @property
    def bad_requests(self) -> List["RequestModel"]:
        """Get bad requests list."""
        return [request for request in self.requests if request.status != 200]

anyrepo/models/user.py
# AnyRepo
# Copyright (C) 2020  Anybox
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


from uuid import uuid4

from flask_login import UserMixin
from werkzeug.security import check_password_hash, generate_password_hash

from anyrepo.models import db


class User(db.Model, UserMixin):
    """User model."""

    id = db.Column(db.Integer, primary_key=True)
    slug = db.Column(
        db.String, nullable=False, default=lambda: uuid4().hex, unique=True
    )
    username = db.Column(db.String, nullable=False, unique=True)
    password_hash = db.Column(db.String, name="password")

    def check_password(self, password: str) -> bool:
        """Check password with stored hash."""
        return check_password_hash(self.password_hash, password)

    def set_password(self, password: str):
        """Hash password and store it in db."""
        self.password_hash = generate_password_hash(password)

anyrepo/api/__init__.py
# AnyRepo
# Copyright (C) 2020  Anybox
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from abc import ABC, abstractmethod
from typing import Optional


class Comment(ABC):
    """API comment wrapper."""

    @property
    @abstractmethod
    def body(self) -> str:
        pass


class Issue(ABC):
    """API issue wrapper."""

    @abstractmethod
    def get_comment_from_body(self, body: str) -> Optional[Comment]:
        pass

    @abstractmethod
    def create_comment(self, body: str):
        pass

    @property
    @abstractmethod
    def state(self):
        pass


class Project(ABC):
    """API project wrapper."""

    @abstractmethod
    def get_issue_from_title(self, title: str) -> Optional[Issue]:
        pass

    @abstractmethod
    def create_issue(self, title: str, body: str):
        pass


class API(ABC):
    """API wrapper."""

    def __init__(self, url: str, token: str):
        self.url = url
        self.token = token

    @abstractmethod
    def get_project_from_name(self, name: str) -> Optional[Project]:
        pass

anyrepo/hooks/__init__.py
# AnyRepo
# Copyright (C) 2020  Anybox
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

anyrepo/views.py
# AnyRepo
# Copyright (C) 2020  Anybox
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from typing import Optional

import ldap
from flask import (
    Blueprint,
    abort,
    current_app,
    flash,
    jsonify,
    make_response,
    redirect,
    render_template,
    request,
    session,
    url_for,
)
from flask_login import LoginManager, current_user, login_required, login_user, logout_user

from anyrepo.forms import ApiForm, HookForm, LoginForm, UserForm
from anyrepo.models import db
from anyrepo.models.api import ApiModel
from anyrepo.models.hook import HookModel
from anyrepo.models.request import RequestModel
from anyrepo.models.user import User

admin = Blueprint("admin", __name__)
login_manager = LoginManager()
login_manager.login_view = "admin.login"


@login_manager.user_loader
def get_user(userid: int) -> Optional[User]:
    """Get user from its id."""
    if "ldap_user" in session:
        return User(username=session["ldap_user"])

    return User.query.get(userid)


@admin.route("/login/", methods=["GET", "POST"])
def login():
    """Login page."""
    form = LoginForm()
    if request.method == "POST" and form.validate_on_submit():
        username = form.username.data
        password = form.password.data

        user = User.query.filter_by(username=username).one_or_none()
        if user and user.check_password(password):
            login_user(user)
            return redirect(url_for("admin.index"))

        if current_app.config.get("LDAP_PROVIDER_URL"):
            conn = ldap.initialize(current_app.config["LDAP_PROVIDER_URL"])
            bind = current_app.config["LDAP_BIND_FORMAT"].format(
                username=username
            )
            try:
                conn.simple_bind_s(bind, password)
                user = User(username=username)
                session["ldap_user"] = username
                login_user(user)
                return redirect(url_for("admin.index"))
            except ldap.INVALID_CREDENTIALS:
                flash("Invalid username or password", "error")
        else:
            flash("Invalid username or password", "error")

    return render_template("login.html", form=form)


@admin.route("/")
@login_required
def index():
    """List admin page."""
    apicount = ApiModel.query.count()
    hookcount = HookModel.query.count()
    usercount = User.query.count()
    badrequests = RequestModel.query.filter(RequestModel.status != 200).count()
    goodrequests = RequestModel.query.filter_by(status=200).count()
    return render_template(
        "index.html",
        apicount=apicount,
        hookcount=hookcount,
        usercount=usercount,
        badrequests=badrequests,
        goodrequests=goodrequests,
    )


@admin.route("/apis/")
@login_required
def apis():
    """List all the registered APIs."""
    apis = ApiModel.query.all()
    return render_template("apis.html", apis=apis)


@admin.route("/api/new/", defaults={"apiuuid": None}, methods=["GET", "POST"])
@admin.route("/api/edit/<apiuuid>/", methods=["GET", "POST"])
@login_required
def api_edit(apiuuid=None):
    """Edit existed api or create a new one."""
    api = (
        ApiModel.query.filter_by(slug=apiuuid).first_or_404()
        if apiuuid
        else ApiModel()
    )
    form = ApiForm(obj=api)
    if request.method == "POST":
        url = form.url.data
        api_id = api.id or 0
        exists = ApiModel.query.filter(
            ApiModel.url == url, ApiModel.id != api_id
        ).one_or_none()
        if exists is not None:
            flash("There is already an API for this url", "error")
        elif form.validate_on_submit():
            api.url = url
            api.name = form.name.data
            api.api_type = form.api_type.data
            api.set_token(form.token.data)
            msg = "API successfully modified"

            if not api.id:
                db.session.add(api)
                msg = "API successfully created"

            db.session.commit()
            flash(msg, "success")
            return redirect(url_for("admin.apis"))
        else:
            for field, errors in form.errors.items():
                flash(f"{form[field].name} : {', '.join(errors)}", "error")

    return render_template("apiform.html", form=form, api=api)


@admin.route("/api/delete/", methods=["POST"])
@login_required
def api_delete():
    """Delete an api from its uuid."""
    apiuuid = request.form.get("slug")
    if not apiuuid:
        abort(404)

    api = ApiModel.query.filter_by(slug=apiuuid).first_or_404()
    db.session.delete(api)
    db.session.commit()
    flash("API successfully removed", "success")
    return redirect(url_for("admin.apis"))


@admin.route("/hooks/")
@login_required
def hooks():
    """List registered hooks."""
    hooks = HookModel.query.all()
    hostname = request.url_root[:-1]
    return render_template("hooks.html", hooks=hooks, hostname=hostname)


@admin.route("/hook/edit/<hookuuid>/", methods=["GET", "POST"])
@login_required
def hook_edit(hookuuid):
    """Edit existed hook or create a new one."""
    hook = HookModel.query.filter_by(slug=hookuuid).first_or_404()
    hostname = request.url_root[:-1]
    form = HookForm(obj=hook)
    if request.method == "POST":
        if form.validate_on_submit():
            hook.set_secret(form.secret.data)
            db.session.commit()
            flash("Hook secret successfully modified", "success")
            return redirect(url_for("admin.hook_detail", hookuuid=hook.slug))
        else:
            for field, errors in form.errors.items():
                flash(f"{form[field].name} : {', '.join(errors)}", "error")

    return render_template(
        "hookform.html", form=form, hook=hook, hostname=hostname
    )


@admin.route("/hook/details/<hookuuid>/")
@login_required
def hook_detail(hookuuid):
    """Show Hook detail."""
    hook = HookModel.query.filter_by(slug=hookuuid).first_or_404()
    hostname = request.url_root[:-1]
    return render_template("hookdetail.html", hook=hook, hostname=hostname)


@admin.route("/users/")
@login_required
def users():
    """List users."""
    users = User.query.all()
    return render_template(
        "users.html",
        users=users,
        ldap=current_app.config.get("LDAP_PROVIDER_URL"),
    )


@admin.route(
    "/user/new/", defaults={"useruuid": None}, methods=["GET", "POST"]
)
@admin.route("/user/edit/<useruuid>/", methods=["GET", "POST"])
@login_required
def user_edit(useruuid=None):
    """Create or edit a user."""
    ldap_provider = current_app.config.get("LDAP_PROVIDER_URL")
    if ldap_provider is not None:
        flash("Users are managed by a LDAP provider", "error")
        return redirect(url_for("admin.users"))

    if useruuid is not None and useruuid != current_user.slug:
        msg = "You can only edit your own data"
        abort(make_response(jsonify(message=msg), 403))

    user = (
        User.query.filter_by(slug=useruuid).first_or_404()
        if useruuid
        else User()
    )
    form = UserForm(obj=user)
    if request.method == "POST":
        userid = user.id or 0
        exists = User.query.filter(
            User.username == form.username.data, User.id != userid
        ).one_or_none()
        if exists is not None:
            flash("There is already a User with this username", "error")
        elif form.validate_on_submit():
            user.username = form.username.data
            user.set_password(form.password.data)
            msg = "User successfully modified"

            if not user.id:
                db.session.add(user)
                msg = "User successfully created"

            db.session.commit()
            flash(msg, "success")
            return redirect(url_for("admin.users"))
        else:
            for field, errors in form.errors.items():
                flash(f"{form[field].name} : {', '.join(errors)}", "error")

    return render_template("userform.html", form=form, user=user)


@admin.route("/user/delete/", methods=["POST"])
@login_required
def user_delete():
    """Delete a user from its uuid."""
    ldap = current_app.config.get("LDAP_PROVIDER_URL")
    if ldap is not None:
        flash("Users are managed by a LDAP provider", "error")
        return redirect(url_for("admin.users"))

    useruuid = request.form.get("slug")
    if not useruuid:
        abort(404)

    count = User.query.count()
    if count == 1:
        msg = "You can not delete the only user"
        abort(make_response(jsonify(message=msg), 403))

    user = User.query.filter_by(slug=useruuid).first_or_404()
    db.session.delete(user)
    db.session.commit()
    flash("User successfully removed", "success")
    return redirect(url_for("admin.users"))


@admin.route("/logout/")
@login_required
def logout():
    """Logout current user."""
    logout_user()
    return redirect(url_for("admin.login"))

anyrepo/templates/apiform.html
{# -*- engine: django -*- #}
{% extends "base.html" %}

{% block content %}
  <header>
    <h1>
      {% if api.id %}
        API {{ api.name }}
      {% else %}
        New API
      {% endif %}
    </h1>
  </header>
  <div class="box">
    <form action="." method="POST">
      {{ form.hidden_tag() }}
      <div>{{ form.name.label }} {{ form.name() }}</div>
      <div>{{ form.url.label }} {{ form.url() }}</div>
      <div>{{ form.api_type.label }} {{ form.api_type(width=20) }}</div>
      <div>{{ form.token.label }} {{ form.token() }}</div>
      <button type="submit" class="btn fullwidth">Submit</button>
    </form>
  </div>
{% endblock %}

anyrepo/templates/apis.html
{# -*- engine: django -*- #}
{% extends "base.html" %}

{% block head %}
  <style lang="css">
  .title {
    margin-bottom: 0;
    margin-top: 0;
    font-weight: bold;
    font-size: 1.4rem;
    margin-right: 2rem;
    margin-left: .5rem;
    text-transform: capitalize;
    color: #2f2f2f;
  }
  .url {
    color: #6f6f6f;
    font-style: italic;
  }
  </style>
{% endblock %}

{% block content %}
  <nav id="path">
    <span class="separator">&gt;</span>
    <a href="{{ url_for('admin.index') }}">Dashboard</a>
    <span class="separator">/</span>
    <span class="selected">Apis</span>
  </nav>
  <header class="flex vcenter spacebetween">
    <h1>APIs</h1>
    <a class="button" href="{{ url_for('admin.api_edit') }}">
      <i class="fas fa-plus"></i>
      Add a new API
    </a>
  </header>
  {% if apis|length == 0 %}
    <p align="center">No APIs registered</p>
  {% else %}
    <form id="deleteform" action="{{ url_for('admin.api_delete') }}" method="POST">
      <input type="hidden" name="slug" id="apislug" value="">
    </form>
    {% for api in apis %}
      <div class="box flex vcenter spacebetween">
        <div class="flex vcenter">
          <i class="fab fa-{{ api.api_type.value }}"></i>
          <span class="title">{{ api.name }}</span>
          <span class="url">{{ api.url }}</span>
        </div>
        <div class="action">
          <a href="{{ url_for('admin.api_edit', apiuuid=api.slug) }}" title="Modify API">
            <i class="fas fa-edit"></i>
          </a>
          <a href="#" title="Delete API" class="error" onclick="deleteAPI('{{ api.slug }}')">
            <i class="fas fa-times error" ></i>
          </a>
        </div>
      </div>
    {% endfor %}
  {% endif %}
{% endblock %}

{% block footer %}
  <script>
  function deleteAPI(value) {
    const inputSlug = document.getElementById('apislug')
    inputSlug.value = value
    document.getElementById('deleteform').submit()
  }
  </script>
{% endblock %}

anyrepo/templates/base.html
{# -*- engine: django -*- #}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Anyrepo</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='fontawesome/css/all.css') }}">
    {% block head %}
    {% endblock %}
  </head>
  <body>
    <div id="main">
      <nav id="leftnav">
        <img src="{{ url_for('static', filename='logo.png') }}"
             id="logo"
             alt="logo">
        <h1>AnyRepo</h1>
        <ul class="links">
          <li>
            <a href="{{ url_for('admin.index') }}" title="Dashboard" class="flex vcenter">
              <i class="fas fa-tachometer-alt"></i>
              Dashboard
            </a>
          </li>
          <li>
            <a href="{{ url_for('admin.apis') }}" title="APIs" class="flex vcenter">
              <i class="fas fa-plug"></i>
              APIs
            </a>
          </li>
          <li>
            <a href="{{ url_for('admin.hooks') }}" title="Hooks" class="flex vcenter">
              <i class="fas fa-network-wired"></i>
              Hooks
            </a>
          </li>
          <li>
            <a href="{{ url_for('admin.users') }}" title="Users" class="flex vcenter">
              <i class="fas fa-user"></i>
              Users
            </a>
          </li>
          <li>
            <a href="{{ url_for('admin.logout') }}" title="Logout" class="flex vcenter">
              <i class="fas fa-sign-out-alt"></i>
              Logout
            </a>
          </li>

        </ul>
      </nav>
      <div id="content">
        {% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
            <ul class="flashes">
              {% for category, message in messages %}
                <li class="{{ category }}">
                  {% if category == 'error' %}
                    <i class="fas fa-times"></i>
                  {% elif category == 'success' %}
                    <i class="fas fa-check"></i>
                  {% else %}
                    <i class="fas fa-info"></i>
                  {% endif %}
                  {{ message }}
                </li>
              {% endfor %}
            </ul>
          {% endif %}
        {% endwith %}
        {% block content %}
        {% endblock %}
      </div>
      {% block footer %}
      {% endblock %}
    </div>
  </body>
</html>

anyrepo/templates/hookdetail.html
{# -*- engine: django -*- #}
{% extends "base.html" %}

{% block head %}
  <style lang="css">
  .requests {
    margin-top: 1.5em;
  }
  .tabs {
    list-style: none;
    margin: .5em 0;
    padding: 0;
    border-bottom: 1px solid var(--divider);
  }
  .tabs li {
    display: inline-block;
    padding: .5em 1em;
    cursor: pointer;
  }
  .tabs .selected {
    color: var(--dark-primary);
    border-bottom: 2px solid var(--dark-primary);
  }
  .tab-content strong {
    display: block;
  }
  .tab-content code {
    padding: .75em;
    background-color: #efefef;
    margin-bottom: .75em;
    margin-top: .75em;
    display: block;
  }
  </style>
{% endblock %}

{% block content %}
  <nav id="path">
    <span class="separator">&gt;</span>
    <a href="{{ url_for('admin.index') }}">Dashboard</a>
    <span class="separator">/</span>
    <a href="{{ url_for('admin.hooks') }}">Hooks</a>
    <span class="separator">/</span>
    <span class="selected">Hook {{ hook.endpoint }}</span>
  </nav>
  <header class="flex vcenter spacebetween">
    <h1>Hook {{ hook.endpoint }}</h1>
    <a class="button" href="{{ url_for('admin.hook_edit', hookuuid=hook.slug) }}">
      <i class="fas fa-edit"></i>
      Modify Hook
    </a>
  </header>
  <div class="flex vcenter">
    <p class="label marginless">Endpoint</p>
    <p class="marginless">{{ hostname }}{{ hook.endpoint }}</p>
  </div>
  <div class="flex vcenter">
    <p class="label marginless">Type</p>
    <p class="marginless">
      <i class="fab fa-{{ hook.hook_type.value }}"></i>
      {{ hook.hook_type.value }}
    </p>
  </div>

  {% if hook.requests|length %}
    <div class="requests">
      <h2>Recent deliveries</h2>
      {% for request in hook.requests[::-1] %}
        <details>
          <summary class="{{ 'success' if request.status == 200 else 'error' }}">
            [{{ request.created_at.strftime("%Y-%m-%d %H:%M:%S") }}]
            {{ request.slug }}
          </summary>
          <div>
            <ul class="tabs" role="tablist">
              <li id="tab-{{ request.id }}-request" class="tab selected">Request</li>
              <li id="tab-{{ request.id }}-response" class="tab">Response</li>
            </ul>
            <div class="tabs-content">
              <div id="tab-{{ request.id }}-request-content" class="tab-content">
                <strong>Headers</strong>
                <code>{{ request.headers }}</code>
                <strong>Body</strong>
                <code>{{ request.body }}</code>
              </div>
              <div id="tab-{{ request.id }}-response-content" class="tab-content" style="display: none">
                <strong>Status {{ request.status }}</strong>
                <code>{{ request.response }}</code>
              </div>
            </div>
          </div>
        </details>
      {% endfor %}
    </div>
  {% endif %}
{% endblock %}


{% block footer %}
  <script>
  document.onreadystatechange = () => {
    if (document.readyState === 'interactive') {
      Array.from(document.getElementsByClassName('tab')).forEach(tab => {
        tab.addEventListener('click', () => {
          const suffix = `-${tab.id.split('-').splice(-1)[0]}`
          const replace = (suffix === '-request') ? '-response' : '-request'

          if (!tab.classList.contains('selected')) {
            tab.classList.add('selected')
            document.getElementById(tab.id.replace(suffix, replace)).classList.remove('selected')
            document.getElementById(`${tab.id}-content`).style.display = 'block'
            document.getElementById(`${tab.id.replace(suffix, replace)}-content`).style.display = 'none'
          }
        })
      })
    }
  }
  </script>
{% endblock %}

anyrepo/templates/hookform.html
{# -*- engine: django -*- #}
{% extends "base.html" %}

{% block content %}
  <nav id="path">
    <span class="separator">&gt;</span>
    <a href="{{ url_for('admin.index') }}">Dashboard</a>
    <span class="separator">/</span>
    <a href="{{ url_for('admin.hooks') }}">Hooks</a>
    <span class="separator">/</span>
    <a href="{{ url_for('admin.hook_detail', hookuuid=hook.slug) }}">Hook {{ hook.endpoint }}</a>
    <span class="separator">/</span>
    <span class="selected">Edit</span>
  </nav>
  <header>
    <h1>Hook {{ hook.endpoint }}</h1>
  </header>
  <div class="box">
    <div class="flex vcenter">
      <p class="label marginless">Endpoint</p>
      <p class="marginless">{{ hostname }}{{ hook.endpoint }}</p>
    </div>
    <div class="flex vcenter">
      <p class="label marginless">Type</p>
      <p class="marginless">{{ hook.hook_type.value }}</p>
    </div>
    <form action="{{ url_for('admin.hook_edit', hookuuid=hook.slug) }}" method="POST">
      {{ form.hidden_tag() }}
      <div>{{ form.secret.label }} {{ form.secret() }}</div>
      <button type="submit" class="btn fullwidth">Submit</button>
    </form>
  </div>
{% endblock %}

anyrepo/templates/index.html
{# -*- engine: django -*- #}
{% extends "base.html" %}

{% block head %}
  <style lang="css">
  .icon {
    font-size: 1.5em;
    margin-right: 1em;
    border-radius: 50%;
    color: white;
    background-color: var(--primary);
    height: 2em;
    width: 2em;
    text-align: center;
    line-height: 2em;
  }
  </style>
{% endblock %}

{% block content %}
  <h1>Dashboard</h1>
  <div>
    <a href="{{ url_for('admin.apis') }}" title="APIs" class="box flex vcenter">
      <i class="fas fa-plug icon"></i>
      <p>{{ apicount }} APIs</p>
    </a>
    <a class="box flex spacebetween" href="{{ url_for('admin.hooks') }}" title="Hooks">
      <div class="flex vcenter">
        <i class="fas fa-network-wired icon"></i>
        <p>{{ hookcount }} Hooks</p>
      </div>
      <div>
        <p class="marginless error">
          {{ badrequests }}
          <i class="fas fa-times"></i>
        </p>
        <p class="marginless success">
          {{ goodrequests }}
          <i class="fas fa-check"></i>
        </p>
      </div>
    </a>
    <a href="{{ url_for('admin.users') }}" title="Users" class="box flex vcenter">
      <i class="fas fa-user icon"></i>
      <p>{{ usercount }} Users</p>
    </a>
  </div>
{% endblock %}